/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexOldImport } from './routes/index-old'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const IndexOldRoute = IndexOldImport.update({
  id: '/index-old',
  path: '/index-old',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/index-old': {
      id: '/index-old'
      path: '/index-old'
      fullPath: '/index-old'
      preLoaderRoute: typeof IndexOldImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/index-old': typeof IndexOldRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/index-old': typeof IndexOldRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/index-old': typeof IndexOldRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/index-old'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/index-old'
  id: '__root__' | '/' | '/index-old'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IndexOldRoute: typeof IndexOldRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IndexOldRoute: IndexOldRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/index-old"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/index-old": {
      "filePath": "index-old.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
